### ISSUE TITLE
Non-base 32 digit found

### ISSUE THREAD

**Issue by joseparreiras** [nabelekt/robinhood_api#1]
I've been trying to use it but I keep getting this error

```
Traceback (most recent call last):
  File "/Users/joseparreiras/Documents/GitHub/robinhood_api/robinhood_process.py", line 406, in <module>
    main()
  File "/Users/joseparreiras/Documents/GitHub/robinhood_api/robinhood_process.py", line 389, in main
    rh_fetch.login()
  File "/Users/joseparreiras/Documents/GitHub/robinhood_api/robinhood_fetch.py", line 18, in login
    totp  = pyotp.TOTP(rh_creds.TOTP_code).now()
  File "/Users/joseparreiras/opt/anaconda3/lib/python3.9/site-packages/pyotp/totp.py", line 46, in now
    return self.generate_otp(self.timecode(datetime.datetime.now()))
  File "/Users/joseparreiras/opt/anaconda3/lib/python3.9/site-packages/pyotp/otp.py", line 40, in generate_otp
    hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
  File "/Users/joseparreiras/opt/anaconda3/lib/python3.9/site-packages/pyotp/otp.py", line 57, in byte_secret
    return base64.b32decode(self.secret, casefold=True)
  File "/Users/joseparreiras/opt/anaconda3/lib/python3.9/base64.py", line 231, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
```

**Comment by nabelekt** [comment]
Hi @joseparreiras. Did you read the README? Particularly:
> To use, put credentials in robinhood_creds.py file.

I am guessing that you still have the placeholder values in that file.
